### PR TITLE
expireCookie now also requires path argument

### PR DESCRIPTION
**Pull request by sopvop**
According to rfc6265 5.3 step 10 [1], a current cookies standard,
cookies are identified by name, path and domain. Thus to properly expire
cookie you need to provide all. Otherwise these are set to current
domain and path. Which makes current implementation of expireCookie
useless. For example logout in Auth snaplet is broken.

[1]: http://tools.ietf.org/html/rfc6265#page-24

### CODE REVIEW

**Comment by reiddraper** [comment]
Cookie expiration also only works if the `httpOnly` and `secure` flags are set as they were when initially issuing the cookie. That is, if you set a cookie with `httpOnly` and/or `secure`, it will not expire if you don't set these same flags. This is currently broken in Snap. To get around it, I just added my own helper which takes an httpOnly and secure parameter.

**Comment by gregorycollins** [comment]
Sorry for the delay in my response, I've been traveling this week (I'm in Zürich until Friday).

The patch no longer cleanly applies, unfortunately, but that's a minor issue. The real problem is deciding what we want this API to look like, and it seems that the way we are currently doing things is broken. With 1.0 around the corner we have an opportunity to fix this going forward.

I like the general idea, and the current patch looks good to me, but as @reiddraper points out we should probably add httpOnly and secure flags to `expireCookieAt`. Also we should probably just go ahead and deprecate `expireCookie`, with a promise that it will be removed by the release of 1.1.0.0.

**Comment by sopvop** [comment]
Sorry for taking that long, was away from haskell dev for a few months.
At this point I wonder if expireCookieAt should rather be this :)
~~~~.haskell
expireCookieAt :: MonadSnap m => Cookie -> m ()`
~~~~

**Comment by ozataman** [comment]
Expiring the cookie is really just adding the same cookie with an old timestamp. I think we should adoptthe signature @sopvop is suggesting; it would simply set a very old timestamp and pass it on to addResponseCookie (as it does now).  This would allow for cleanly getting the cookie from existing set of cookie (by name in the common scenario) and passing it directly to expire:

```getCookie "foo" >>= maybe (return ()) expireCookie```

I find the -at suffix unnecessary. If an expire time is to be specified, the user can just use addResponseCookie to set the modified ```Cookie```.

**Comment by sopvop** [comment]
At suffix was about cookie path initially. Still need a good name. (or just break stuff because 1.0)

**Comment by gregorycollins** [comment]
"Break stuff because 1.0" is not a bad answer here. Probably we should not break the old function outright but should deprecate it and add a new one in its stead.

**Comment by sopvop** [comment]
Any name bikeshedding? I'm not very happy with addExpiredCookie myself.

**Comment by gregorycollins** [comment]
You know what? I've changed my mind, just obliterate the existing function. Given that it was completely broken to begin with, I think I want users to have to fix their code here, and the bump to 1.0 offers a good excuse.

**Pull request merged**
