### PR TITLE
Bump the dependency on 'monad-control'.

### PR DESCRIPTION
**Pull request by 23Skidoo**

### CODE REVIEW

**Comment by 23Skidoo** [comment]
@gregorycollins Ping.

**Comment by hvr** [comment]
but why restrict artificially to `monad-control >= 1` (and hence increase the install-plan conflict risk) if it's easy to support older versions?

**Comment by 23Skidoo** [comment]
Because supporting only `monad-control >= 1` is easier (I only need to test with one version) and makes code cleaner.

**Comment by hvr** [comment]
That's obviously true, but otoh there's still enough packages out there which constraint to `monad-control < 1`:  http://packdeps.haskellers.com/reverse/monad-control

**Comment by 23Skidoo** [comment]
@hvr How many of them depend on `snap >= 1.0`?

**Comment by gregorycollins** [comment]
We haven't depended on old versions of monad-control in the past so I think I'm ok with starting our dependency at 1.0.

**Pull request merged**
